[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[images]
  remote_images = [
    "https://storage.googleapis.com/pineville-rug/.*",
    "https://cdn.photoproofpro.com/.*"
  ]
